### PR TITLE
Task List Rails Wave 3

### PR DESCRIPTION
**Pull request by sallyamoore**
Completed Wave 3. I had some difficulty with routes for updating a task once I added a partial. My Adie mentor, Linnea, taught be about naming paths in routes.rb, which solved the problem (although I also could've done it with a conditional in my partial).

I love that clicking on the checkbox in the index table updates the completion info. Pretty cool.

Learning rails has been pretty challenging, but I _think_ I'm starting to understand how it works... Fingers crossed for the next wave...

### CODE REVIEW

**Comment by sallyamoore** [comment]
Completed Wave 4. My app is deployed through heroku at https://agile-ravine-7276.herokuapp.com/. This wave was challenging to complete in a short amount of time, but all the functionality is there. Yay! I finished it all! I wish I'd had more time to work on the appearance of the site, DRY up code, and improve on some of the features. 

I'm glad I'll get a lot more practice with Rails. It still seems like a lot of dark magic at this point. I want to understand all the things!

**Comment by roseaboveit** [comment]
I'm going to start with comments to the stuff already merged. It is hard to track things there but I pulled it down onto my computer so I could just look through the files. These upcoming broader comments are not about your final project, just about the first stages.

**Comment by roseaboveit** [comment]
Tasks controller Index method. You have `render :index`. This is not explicitly necessary. If you are rendering a template withe the same name as the method rails just knows what to do. That is why it works for show and new as well.

**Comment by roseaboveit** [comment]
In the Tasks controller Show method. You don't need to set id first. you can dry it up and have a single line. Look at how you do the Destroy method for a hint.

**Comment by roseaboveit** [comment]
Your strong params are well written. Nit picky thing that doesn't really matter. Conventionally, I've always seen the name of that method as the model_params so in this case `task_params`. What you have totally works and create_params is clear about what it is doing. So Good Job!

**Comment by roseaboveit** [comment]
Concerning this code snippet from the tasks/index.html.erb file:

<% completed_tasks = [] %>
<% incomplete_tasks = [] %>
<% @tasks.each do |task| %>
<%   if task[:date_completed] != nil %>
<%     completed_tasks.push(task) %>
<%   else %>
<%     incomplete_tasks.push(task) %>
<%   end %>
<% end %>

This chunk is well written. However, it does clutter up your views. You want to keep as much logic as possible out of your views as possible. That way you can keep your mind mostly thinking about display when you are looking at view files.

A good first step to refactoring would be to move this code into the controller method and storing results in an instance variable that will make it accessible to the view.

A good next step would be to pull out code into another method that is called in the parent method.

Super Awesome Bonus Points would be to figure out how to move this into the model.

**Pull request merged**
